# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ringo/scientific-linux-7.1'
  config.vm.network 'private_network', ip: '192.168.33.10'
end
